// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xwwvhlwoxmbczqkcxqxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3d3ZobHdveG1iY3pxa2N4cXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM1MTk5MjEsImV4cCI6MjA3OTA5NTkyMX0.G4HNMKJLFlt4YSo9ihqnz5b5oHaMZxCnrf8XlTSSWos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);